### ISSUE TITLE
Multiple Errors 8.0

### ISSUE THREAD

**Issue by Korrigan1340** [funkydude/BugSack#11]
118x Couldn't open ElvUI\
!BugGrabber\BugGrabber.lua:578: in function <!BugGrabber\BugGrabber.lua:578>

20x Deferred XML Node object named Lib_UIDropDownListTemplate already exists
!BugGrabber\BugGrabber.lua:578: in function <!BugGrabber\BugGrabber.lua:578>

20x Deferred XML Node object named Lib_UIDropDownMenuTemplate already exists
!BugGrabber\BugGrabber.lua:578: in function <!BugGrabber\BugGrabber.lua:578>

38x Deferred XML Node object named Lib_UIDropDownMenuButtonTemplate already exists
!BugGrabber\BugGrabber.lua:578: in function <!BugGrabber\BugGrabber.lua:578>

**Comment by funkydude** [comment]
Invalid, not a BugSack issue.

**Comment by Korrigan1340** [comment]
Lol..yea  but you own both and dont allow errors on buggrabber. ironic actually

**Comment by funkydude** [comment]
It's not a buggrabber issue either.

There's nothing ironic about not having an issue tracker for buggrabber, it's to stop exactly this from happening. People think they need to report errors to me and not to authors.
