### ISSUE TITLE
Can't see the complete bug log

### ISSUE THREAD

**Issue by Psychoian** [funkydude/BugSack#112]
## Describe the problem
Sometimes the Bugsack log will hide the content use "...". How to fix it to see the complete log?

**38x ...er**Spells/ClassTalents/Blizzard_ClassTalentsFrame.lua:727: bad argument #1 to 'upper' (string expected, got no value)
[string "=[C]"]: in function upper'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua"]:727: in function RefreshCurrencyDisplay'
[string "@Blizzard_PlayerSpells/ClassTalents/Blizzard_ClassTalentsFrame.lua"]:1353: in function UpdateInspecting'
[string "@Blizzard_PlayerSpells/Blizzard_PlayerSpellsFrame.lua"]:257: in function SetInspecting'
[string "@Blizzard_PlayerSpells/Blizzard_PlayerSpellsFrame.lua"]:220: in function SetInspectUnit'
[string "@Blizzard_FrameXMLUtil/Mainline/PlayerSpellsUtil.lua"]:9: in function <.../Blizzard_FrameXMLUtil/Mainline/PlayerSpellsUtil.lua:7>
[string "@Blizzard_FrameXMLUtil/Mainline/PlayerSpellsUtil.lua"]:33: in function OpenToClassTalentsTab'
[string "@Blizzard_InspectUI/InspectPaperDollFrame.lua"]:207: in function <Blizzard_InspectUI/InspectPaperDollFrame.lua:202>

Locals:
(*temporary) = "string expected, got no value"

### What steps will reproduce the problem?

1.  
2.  
3.

**Comment by funkydude** [comment]
Not a BugSack issue.
