### ISSUE TITLE
Error with BugGrabber via another addon

### ISSUE THREAD

**Issue by TheCheat54** [funkydude/BugSack#113]
I've very recently (since the 9/25 update to BugGrabber) been encountering an issue combined with Altoholic (hasn't been updated since 9/15) where splitting stacks in my warband bank causes an error to be thrown claiming Altoholic is the cause, but BugGrabber's code is actually the named execution. Is this because BG is attempting to stop another addon's action that it believes is bad? The way the code is structured lends itself to that but I don't want to assume. Below is the full output of the error. Altoholic hasn't caused issues with stack-splitting in the warbank before, so this seems like a false positive if BG is the one stopping it.

```
[ADDON_ACTION_FORBIDDEN] AddOn 'Altoholic' tried to call the protected function 'RunBinding()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `RunBinding'
[string "@Blizzard_FrameXML/Mainline/StackSplitFrame.lua"]:196: in function <...ddOns/Blizzard_FrameXML/Mainline/StackSplitFrame.lua:193>
[string "=[C]"]: in function `Hide'
[string "@Blizzard_FrameXML/Mainline/StackSplitFrame.lua"]:235: in function `StackSplitOkayButton_OnClick'
[string "@Blizzard_FrameXML/Mainline/StackSplitFrame.lua"]:165: in function <...ddOns/Blizzard_FrameXML/Mainline/StackSplitFrame.lua:141>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:491
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:491
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:557
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:557
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:551
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:566
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:511
}
```

To reproduce:
1. With BG and Altoholic installed (and the latter's account-wide inventory tracking enabled, which is default), open the bank from any bank source (NPC, Jeeves, etc).
2. Switch to the warband bank tab.
3. Attempt to split an item stack and put the result either in the tab or in the character's bags.
4. Repeat step 4, where the error is thrown on the second and all subsequent attempts until the UI is reloaded.

**Comment by funkydude** [comment]
Not a BugSack or BuggGrabber issue.
