### ISSUE TITLE
Enhancement Request (Non-Issue)

### ISSUE THREAD

**Issue by amber1019** [funkydude/BugSack#15]
Wasn't sure where to put requests, if you take them. So I'll post it here.

It would be absolutely wonderful if when we pull up the bugsack (/bugsack show) if there was a "wipe bugs" button to use. That way we don't have to do "/bugsack show" and then "/bugsack" again to hit the "wipe saved bugs" button.
I know that you actually have to /reload and/or fix the bugs or uninstall the addon causing the bugs... all that stuff.
But a "wipe bugs" button on the actual window would be totally great and super useful. Please consider this for a future update.

**Comment by funkydude** [comment]
No plans for this. I don't really want to encourage just wiping bugs that might be useless at a later date. I think people would just that clicking it out of habbit without thinking.
