### ISSUE TITLE
WoW Classic 1.13.2

### ISSUE THREAD

**Issue by spiken112** [funkydude/BugSack#18]
Will you add support for BugSack and Buggrabber for WoW Classic 1.13.2 ?

**Comment by funkydude** [comment]
Works fine.

**Comment by alexejk** [comment]
Can this be published on Curse as classic-supported?

**Comment by funkydude** [comment]
Eventually yes, but it works fine for now.

**Comment by alexejk** [comment]
It works, just not installable via curse client for classic and thus discovery does not work well :)

**Comment by Altoholic** [comment]
Can confirm it work fine.
Can confirm having it in wow classic twitch would be more convenient ^^
