### ISSUE TITLE
Minimap Button Stays Even When Disabled In Classic

### ISSUE THREAD

**Issue by wheatbread** [funkydude/BugSack#20]
I'm not sure if this is intended behavior, but unchecking the 'minimap icon' option just fades out the button instead of disabling it. 

So whenever I mouse over the minimap, the bugsack icon appears and hangs around for a bit.  

Would there be a way to actually disable it?  I already have it on the databroker, so I would like my minimap to be completely clear.

**Comment by funkydude** [comment]
Just tested it on Classic and it works perfectly fine. This is most likely a conflict with another addon. You can find out which addon by disabling them in the addons menu. Post back here with which addon was responsible.

**Comment by funkydude** [comment]
No response, closing.
