### ISSUE TITLE
I have a feeling these are all bugsack related, but I'm not a 100%

### ISSUE THREAD

**Issue by ANaPhOrAX** [funkydude/BugSack#22]
1x [ADDON_ACTION_BLOCKED] AddOn 'Ace3' tried to call the protected function 'SetTargetClampingInsets()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetTargetClampingInsets'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:274: in function `SetupClassNameplateBars'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:96: in function `OnNamePlateAdded'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:51: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:42>

Locals:
InCombatSkipped

-------------------------------------------------------------------------------------------

5x ...eBlizzard_NamePlates\Blizzard_NamePlates.lua:185: Usage: GetRaidTargetIndex(unit)
[C]: in function `GetRaidTargetIndex'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:185: in function `OnRaidTargetUpdate'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:99: in function `OnNamePlateAdded'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:51: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:42>

Locals:
(*temporary) = nil

-------------------------------------------------------------------------------------------

1x ...eBlizzard_NamePlates\Blizzard_NamePlates.lua:443: Action[FrameMeasurement] failed because[Can't measure restricted regions]: attempted from: <unnamed>:GetLeft().
[C]: in function `GetLeft'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:443: in function `GetPreferredInsets'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:138: in function `UpdateInsetsForType'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:122: in function `ApplyFrameOptions'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:93: in function `OnNamePlateAdded'
...eBlizzard_NamePlates\Blizzard_NamePlates.lua:51: in function <...eBlizzard_NamePlates\Blizzard_NamePlates.lua:42>

Locals:
(*temporary) = <unnamed> {
 otherHealPrediction = <unnamed> {
 }
 b = 1
 myHealAbsorbLeftShadow = <unnamed> {
 }
 border = <unnamed> {
 }
 background = <unnamed> {
 }
 overAbsorbGlow = <unnamed> {
 }
 barTexture = <unnamed> {
 }
 0 = <userdata>
 r = 0.667000
 totalAbsorb = <unnamed> {
 }
 myHealPrediction = <unnamed> {
 }
 g = 0.667000
 totalAbsorbOverlay = <unnamed> {
 }
 myHealAbsorbRightShadow = <unnamed> {
 }
 overHealAbsorbGlow = <unnamed> {
 }
 myHealAbsorb = <unnamed> {
 }

**Comment by funkydude** [comment]
Not a BugSack problem.
