### ISSUE TITLE
Bug report.

### ISSUE THREAD

**Issue by a268-Beefy** [funkydude/BugSack#24]
No idea what is wrong with it but BugSack reports me an Error:

2x BugSack\Libs\AceComm-3.0\ChatThrottleLib-23.nil.lua:216: hooksecurefunc(): SendAddonMessage is not a function
[C]: in function `hooksecurefunc'
BugSack\Libs\AceComm-3.0\ChatThrottleLib-23.nil.lua:216: in function `Init'
BugSack\Libs\AceComm-3.0\ChatThrottleLib-23.nil.lua:512: in main chunk

Locals:

**Comment by funkydude** [comment]
Not a BugSack problem.
