### ISSUE TITLE
LUA error, sort of

### ISSUE THREAD

**Issue by raysmith59** [funkydude/BugSack#25]
This is BugGrabber related but that add-on doesn't have its own issues function so reporting it here.

Seems there are scenarios where that code line isn't working correctly, considering I've apparently had this happen 603 times I wouldn't mind some sort of protection be added so it doesn't show up for me when it happens.

603x (null)
!BugGrabber\BugGrabber.lua:578: in function <!BugGrabber\BugGrabber.lua:578>

**Comment by funkydude** [comment]
Not a BugSack problem.
