### ISSUE TITLE
Left Click to drag and Right Click for options don't work on title bar

### ISSUE THREAD

**Issue by CMcFadyen** [funkydude/BugSack#26]
When you mouse over the title of the BugSack window, you get the "Quick tips" tooltip that says you can left click to drag the window or right click to open the interface options.  While this tooltip is up, left click and right click do not in fact do anything.  There is a tiny margin around the scrollable text window which you can drag from, but right clicking that doesn't do anything.

Double click to filter does work.

**Comment by Walkerbo** [comment]
This please.

The drag only works on the very top right on the number of errors text.
It would be great if we could just drag the whole frame.
