### ISSUE TITLE
party members changed

### ISSUE THREAD

**Issue by Kodatora** [funkydude/BugSack#27]
i get this same error over and over.  Any idea?

5x wMarker\config.lua:745: Attempt to register unknown event "PARTY_MEMBERS_CHANGED"
[string "=[C]"]: in function `RegisterEvent'
[string "@wMarker\config.lua"]:745: in main chunk

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = "PARTY_MEMBERS_CHANGED"

**Comment by funkydude** [comment]
Not a BugSack issue.
