### ISSUE TITLE
Make BugSack available for WoW classic on curseforge

### ISSUE THREAD

**Issue by dfherr** [funkydude/BugSack#28]
It would be nice if BugSack and BugGrabber could be made available for wow classic on curseforge. 

Both addons work fine, you just need to upload version for Classic and change the toc to `Interface: 11304`

**Comment by boktai1000** [comment]
Any traction on this? What is the context "Buggrabber and there is currently no simple way to have a classic version of that" https://github.com/funkydude/BugSack/pull/37#issuecomment-708095972

As far as I'm aware, this is the only Bug grabbing addon that works with Classic, so having it compatible out of the box (and with Addon updaters/installers) would definitely help, especially if it works fine or with a slight toc change.

**Comment by Altoholic** [comment]
Any update on that ?
I'm still upgrading Buggraber by hand (contrary to Bugsack, who is handled well by Ajour manager - who take it from WoWinterface).
And all is working well... lazy me just want an automatic update ^^

**Comment by funkydude** [comment]
BugSack was done a while ago, BugGrabber is now done.
