### ISSUE TITLE
Fix for lua errors on beta

### ISSUE THREAD

**Issue by flow0284** [funkydude/BugSack#29]
Go to line 313 and change:
`searchBox = CreateFrame("EditBox", nil, window)`
to
`searchBox = CreateFrame("EditBox", nil, window, BackdropTemplateMixin and "BackdropTemplate")`

Go to line 323 and change:
`edgeSize = 0,`
to
`edgeSize = 1,`

**Comment by gixxpunk** [comment]
https://github.com/funkydude/BugSack/pull/30

**Comment by lotsoftoons** [comment]
Damn. You beat me to it. I got the same results by changing edgeSize to nil.
