### ISSUE TITLE
Slash command to clear errors

### ISSUE THREAD

**Issue by AlexL1118** [funkydude/BugSack#39]
Can we please have a slash command to clear errors for using this command in a macro?
Something like "/swatter clear", but for BugSack.

**Comment by funkydude** [comment]
But why? Slash commands are for something you do frequently. If you're frequently clearing errors, it sounds that you've picked up a bad habit?

**Comment by AlexL1118** [comment]
I do this several times per minute during whole evening when I'm debugging issues in some addon (like https://github.com/Spillmaker/Bagnon_Currencies/issues/4) - just to see only current bugs, without error messages of previous variants.

**Comment by funkydude** [comment]
You can use `/run BugSack:Reset()`
