### ISSUE TITLE
Option to set custom "sack" window width/height

### ISSUE THREAD

**Issue by Amadeus-** [funkydude/BugSack#41]
I was thinking that with monitors and resolutions as they are today, have a much larger "sack window" would be nice for being able to make it so that each line of the stack trace could be individual calls (i.e., make the stack trace easier to read.)    Right now I find myself having to copy/paste the sack text into another editor just so my eyes can better parse it.

Would there be an interest in a pull request to add this functionality?   I was thinking of just adding two configuration options:  one for width and one for height with a box to type in the static integer.    The default would stay as it is right now.

Or, if the addon author would prefer to do it, that's fine with me too.   I just think the sack could be a lot more useful if it were bigger on the screen, and think that we're now to the point at which monitors and resolutions can handle a sack that's both wider and taller.

Thanks.

**Comment by Walkerbo** [comment]
I second this request.

I would also like the frame to open to its last position instead of always displaying in the center.

**Comment by SinusPi** [comment]
A recent commit makes the window larger by default, perhaps that helps a bit?

**Comment by Walkerbo** [comment]
Thaks the bigger window does help :)
