### ISSUE TITLE
Get everytime this error from bugsack, but i can't relate to a addon

### ISSUE THREAD

**Issue by Sekorhex** [funkydude/BugSack#43]
16x FrameXML\PartyUtil.lua:51: bad argument #2 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@FrameXML\PartyUtil.lua"]:51: in function <FrameXML\PartyUtil.lua:43>
[string "=(tail call)"]: ?
[string "@FrameXML\PartyMemberFrame.lua"]:352: in function `PartyMemberFrame_UpdateNotPresentIcon'
[string "@FrameXML\PartyMemberFrame.lua"]:439: in function `PartyMemberFrame_OnEvent'
[string "*:OnEvent"]:1: in function `OnEvent'
[string "@FrameXML\UnitFrame.lua"]:921: in function <FrameXML\UnitFrame.lua:919>

Locals:
(*temporary) = "%s

%s"
(*temporary) = "Ihr seid derzeit in |cffffffffZeitwanderungskampagnen: Die Legionsinvasion|r"
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by funkydude** [comment]
This error has nothing to do with BugSack. BugSack just collects errors.
