### ISSUE TITLE
Request to ignore 'usual' errors that don't impede on gameplay

### ISSUE THREAD

**Issue by jonomurphy** [funkydude/BugSack#45]
Not so much a problem, but very often I have errors pertaining to Raidcompactframe/tried to call the protected function that don't seem to do much but would be nice to sorta 'ignore'.

**Comment by funkydude** [comment]
As much of a problem that taint may be for the inexperienced devs to try to track down and resolve, it's still an issue that should not be ignored, sorry. If authors are struggling to resolve such issues they should try contacting developer Discord servers for assistance.
