### ISSUE TITLE
!BugGrabber needs an updated .toc for Burning Crusade Classic

### ISSUE THREAD

**Issue by b-morgan** [funkydude/BugSack#47]
## Describe the problem
Blizzard's message about a new version of WoW will disable any addon that doesn't have an up-to-date .toc file, i.e. "##Interface: 20501".

BugSack has been fixed but !BugGrabber needs one as well.

### What steps will reproduce the problem?

1.  Download current versions of BugSack (for BCC) and !BugGrabber (only one version available).
2.  Start WoW BCC
3.  Let WoW disable obsolete addons.
4. Find a bug

### What version of the addon are you using? (Stating 'latest' is not useful)
BugSack 9.0.3 with "## Interface: 20501"
!BugGrabber 9.0.2 with "## Interface: 90005"

### Do you have an error log of what happened?
No

### Any additional information? (example: WoW language if not English)
Changing the .toc file fixes the issue.

**Comment by funkydude** [comment]
Not a BugSack issue. I'm also well aware.

**Comment by Mushoz** [comment]
@funkydude You are the developer and maintainer of both BugSack and BugGrabber, correct? I wasn't able to find an issue tracker for BugGrabber, but it would be very much appreciated if it could also get an updated .toc file. BugSack is already available for classic through addon managers, but BugGrabber unfortunately isn't. Having said that, BugGrabber works perfectly from what I can tell, so I think the current version could be shipped for classic just fine.
