### ISSUE TITLE
change of function

### ISSUE THREAD

**Issue by amey1956** [funkydude/BugSack#48]
## Describe the problem
formerly alt-click would clear the bug sack icon, as of last update it opens the bug report. shift click reloads ui, as before. control-click shows the report window, alt-click is duplicating control-click

### What steps will reproduce the problem?

1.  alt-click icon - see report popup
2.  
3.  

### Do you have an error log of what happened?
there is no error, just a change of function - perhaps by mistake

**Comment by funkydude** [comment]
A discussion on this already exists.
