### ISSUE TITLE
BugGrabber could really use the new multiple .toc feature

### ISSUE THREAD

**Issue by b-morgan** [funkydude/BugSack#49]
## Describe the problem

BugGrabber only has one .zip file on CurseForge with a single .toc containing ## Interface: 90005 (retail). If there were three .toc files, !BugGrabber.toc, !BugGrabber-bcc.toc, and !BugGrabber-classic.toc, with the ## Interface: set appropriately in each, then BugGrabber would be up-to-date on all three versions of WoW automagically. This is a new feature from Blizzard that I don't think has been widely publicized. See [https://www.wowinterface.com/forums/showthread.php?t=58747&highlight=multiple+toc+files](url).

In these uncertain times just after Blizzard has released Burning Crusade Classic, Blizzard wants to disable all out of date addons. Clicking Load Anyway will fix BugGrabber, but also allow any other addons that have not been updated to load potentially causing all sorts of errors.

### What steps will reproduce the problem?

1.  Install BugSack and BugGrabber on all three flavors of WoW
2.  BugGrabber is out-of-date on BCC
3. BugGrabber is out-of-date on Classic
3. BugGrabber is completely operational on Retail 

### What version of the addon are you using? (Stating 'latest' is not useful)
v9.0.2 dated March 27, 2021.

### Do you have an error log of what happened?
N/A

### Any additional information? (example: WoW language if not English)
Alternate Plan B would be to publish three versions of BugGrabber just like BugSack.

**Comment by boktai1000** [comment]
Second this - I came to grab the addon for BC and noticed this back in Classic as well. I came to write this issue myself but noticed you already did it, so I'm going to +1 your request.

**Comment by Bananaman** [comment]
Yep, for now I've manually changed the version in the TOC file of BugGrabber. But the multi-TOC system would be ideal as an official solution.

**Comment by MyTechnoHunter** [comment]
agreed with the above, works fine by adding the needed .toc files (simple fix)

**Comment by funkydude** [comment]
New version now has multiple toc files.

**Comment by b-morgan** [comment]
I see the multiple .toc files in the BugSack zip files but their names are NOT the names Blizzard is looking for so they probably won't work. In addition, this issue was about BugGrabber and I can't find an updated release for it.

**Comment by Bananaman** [comment]
@b-morgan Please do a few seconds of Google research before saying things like that. :P

The new filenames at https://github.com/funkydude/BugSack are correct.

https://wowpedia.fandom.com/wiki/TOC_format

https://github.com/Stanzilla/WoWUIBugs/issues/68#issuecomment-889431675

**Comment by Bananaman** [comment]
> I was talking about BugGrabber, which was updated and is visible on the CurseForge website. But there seems to be some caching issues with the latest zip being picked up by the app.

Yeah. He could have just checked https://github.com/funkydude/BugSack/releases which shows a new release before his rude and stupid post.

Thanks a lot for the new release! 🙏❤️

**Comment by funkydude** [comment]
@Bananaman I think you mean https://www.curseforge.com/wow/addons/bug-grabber/files as your link is BugSack not BugGrabber.

**Comment by Bananaman** [comment]
@funkydude Ah, right. I was checking this commit in this repo:

https://github.com/funkydude/BugSack/commit/712ec6909b2a495722d2024e244380ba2ecb9654

But either way the TOC filenames you are using are correct! :D

**Comment by b-morgan** [comment]
@funkydude Thanks for fixing it. I'll just wait until the update shows up in the usual places.
