### ISSUE TITLE
hi is this a error?

### ISSUE THREAD

**Issue by XuoMauz** [funkydude/BugSack#5]
216x SharedXML\SharedUIPanelTemplates.lua:672: Attempt to access forbidden object from code tainted by an AddOn
[C]: in function `IsOwned'
SharedXML\SharedUIPanelTemplates.lua:672: in function `PanelTemplates_SelectTab'
BugSack\sack.lua:118: in function <BugSack\sack.lua:32>
BugSack\sack.lua:445: in function <BugSack\sack.lua:440>
BugSack\sack.lua:464: in function `OpenSack'
BugSack\core.lua:59: in function <BugSack\core.lua:46>
[string "safecall Dispatcher[2]"]:4: in function <[string "safecall Dispatcher[2]"]:4>
[C]: ?
[string "safecall Dispatcher[2]"]:13: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
!BugGrabber\BugGrabber.lua:149: in function <!BugGrabber\BugGrabber.lua:147>
!BugGrabber\BugGrabber.lua:370: in function <!BugGrabber\BugGrabber.lua:292>
...
[C]: ?
[string "safecall Dispatcher[3]"]:13: in function `?'
...ist\libs\CallbackHandler-1.0\CallbackHandler-1.0-6.lua:90: in function `Fire'
...s\AckisRecipeList\libs\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...s\AckisRecipeList\libs\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `UseAction'
FrameXML\SecureTemplates.lua:346: in function `handler'
FrameXML\SecureTemplates.lua:619: in function `SecureActionButton_OnClick'
FrameXML\ActionButton.lua:100: in function <FrameXML\ActionButton.lua:94>
FrameXML\ActionButton.lua:136: in function `ActionButtonDown'
[string "ACTIONBUTTON2"]:2: in function <[string "ACTIONBUTTON2"]:1>

**Comment by funkydude** [comment]
What are you doing?
This addon collects errors in other addons.
Do not report them here, report them to the addon author.
