### ISSUE TITLE
Error each time I log in

### ISSUE THREAD

**Issue by GaryREM** [funkydude/BugSack#53]
## Describe the problem
Bugsack generating error each time I log in

### What steps will reproduce the problem?

1.  log in

### What version of the addon are you using? (Stating 'latest' is not useful)
9.1.1-classic

### Do you have an error log of what happened?
BugSack-v9.1.1\core.lua:130: attempt to call method 'GetSessionId' (a nil value)

**Comment by funkydude** [comment]
@GaryREM I have no idea what would cause this. I'm going to assume it doesn't happen if you have only BugGrabber and BugSack enabled on their own. I would start there then gradually enable a bunch of addons at a time until the issue returns. That should help you isolate what addon is causing it and then you can report it to me so I can reproduce the issue.

**Comment by funkydude** [comment]
No response, closing.
