### ISSUE TITLE
Local error 

### ISSUE THREAD

**Issue by lectrcsprx** [funkydude/BugSack#55]
## Describe the problem
Setpoint error.

### What steps will reproduce the problem?

1.  Logging in
2.  
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)
Version 2.52

### Do you have an error log of what happened?
1x Interface_TBC\FrameXML\UIParent.lua:2535: Action[SetPoint] failed because[SetPoint would result in anchor family connection]: attempted from: QuestWatchFrame:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@Interface_TBC\FrameXML\UIParent.lua"]:2535: in function `UIParentManageFramePositions'
[string "@Interface_TBC\FrameXML\UIParent.lua"]:1827: in function <Interface_TBC\FrameXML\UIParent.lua:1814>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface_TBC\FrameXML\UIParent.lua"]:2546: in function `UIParent_ManageFramePositions'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetBelowMinimapFrame.lua"]:25: in function `layoutFunc'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:225: in function `UpdateWidgetSetContainerLayout'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:318: in function `ProcessWidgetSet'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:340: in function `UpdateAllWidgets'
[string "@Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua"]:33: in function <...dOns\Blizzard_UIWidgets\Blizzard_UIWidgetManager.lua:31>

Locals:
(*temporary) = QuestWatchFrame {
 0 = <userdata>
 FadeOut = <unnamed> {
 }
 FadeIn = <unnamed> {
 }
}
(*temporary) = "TOPRIGHT"
(*temporary) = "MinimapCluster"
(*temporary) = "BOTTOMRIGHT"
(*temporary) = 0
(*temporary) = 0

**Comment by funkydude** [comment]
Not a BugSack issue.
