### ISSUE TITLE
Bug Grabber! not on github

### ISSUE THREAD

**Issue by kingreboot** [funkydude/BugSack#63]
I been using your github to download and update BugSack, but I can't find Bug Grabber. Any chance you would host it here

**Comment by sigprof** [comment]
There is another source for the BugGrabber addon that could be used by WowUp: https://www.wowinterface.com/downloads/info23141-BugGrabber.html, but the addon version there is outdated (9.2.2, while Curse has 9.2.5). If for any reason you don't want to host BugGrabber on GitHub, could you please update the addon on WowInterface at least?

(Also the BugGrabber page on WowInterface page suggests to report issues at https://www.wowace.com/addons/bug-grabber/tickets/, but apparently that bugtracker no longer exists; the Curseforge page for BugGrabber does not show any way to report issues at all.)
