### ISSUE TITLE
Raid Boss Artificer Xy' mox NPCs

### ISSUE THREAD

**Issue by CMRW** [funkydude/BugSack#64]
Hi wanted to let you know when you click on the npcs in the Artificer Xy' mox fight Hekili doesn't seem to work or it will show buttons to push but only rarely but clicking on Artificer Xy' mox it shows. Wasn't sure if you knew about that or not but I don't have a screenshot to show it.

**Comment by funkydude** [comment]
Unrelated to BugSack.
