### ISSUE TITLE
Host BugGrabber on Github also?

### ISSUE THREAD

**Issue by btnmasher** [funkydude/BugSack#65]
## Describe the problem

Since this addon requires BugGrabber to function, and you are the author of both addons, would it be too munch to ask to host this on github as well? Addon updating is in a poor state now with the purchase of CurseForge by Overwolf and many not wishing to expose their machines to Overwolf's spyware in order to simply update addons conveniently. Many are turning to direct github releases, and addon updater tools are following suit now that they have been cut off from the CurseForge API. Thanks in advanced!

**Comment by dblanch369** [comment]
yes, PLEASE :)
