### ISSUE TITLE
[LUA Error] AceSerializer-3.0-5.lua:247: bad argument #1 to 'gsub' (string expected, got nil)

### ISSUE THREAD

**Issue by boktai1000** [funkydude/BugSack#66]
## Describe the problem

Lua Error: `7x ...BugSack\Libs\AceSerializer-3.0\AceSerializer-3.0-5.lua:247: bad argument #1 to 'gsub' (string expected, got nil)`

### What steps will reproduce the problem?

1.  Happened randomly in SWP after looting badges after defeating Kalecgos, not immediately after but that's where I was when it happened

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

![image](https://user-images.githubusercontent.com/9054563/182503312-2d843700-9237-4ddd-ab0d-d7fcd46c4a88.png)

### What version of the addon are you using? (Stating 'latest' is not useful)

9.2.4

### Do you have an error log of what happened?
```

7x ...BugSack\Libs\AceSerializer-3.0\AceSerializer-3.0-5.lua:247: bad argument #1 to 'gsub' (string expected, got nil)
[string "=[C]"]: ?
[string "@BugSack\Libs\AceSerializer-3.0\AceSerializer-3.0-5.lua"]:247: in function `Deserialize'
[string "@Details\core\network.lua"]:404: in function `func'
[string "@Details\core\network.lua"]:648: in function `?'
[string "@AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...sic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Attune\Libs\AceComm-3.0\AceComm-3.0-12.lua"]:218: in function `OnReceiveMultipartLast'
[string "@Attune\Libs\AceComm-3.0\AceComm-3.0-12.lua"]:256: in function <...rfaceAttune\Libs\AceComm-3.0\AceComm-3.0.lua:246>
```

### Any additional information? (example: WoW language if not English)

Mentions of **Attune** in the Lua Error report, I should note that I have had Attune actually uninstalled for months now. For what it's worth. I am using Details currently, and Atlas Loot Classic which are both mentioned, the latest of both / all Addons. And no changes to those versions in recent time (neither has been updated recently, first time this has popped for this)

**Comment by funkydude** [comment]
Attune was clearly loaded, but the error appears to be from Details.

**Comment by boktai1000** [comment]
For what it's worth though, I don't have a trace of Attune in my entire `_classic_` directory. Including any leftover SavedVariables, but if the culprit is indeed Details then maybe it's just a side effect of Details in some way.

![image](https://user-images.githubusercontent.com/9054563/182682984-f4fa615d-3265-40b7-a31a-09ab133b841b.png)

**Comment by funkydude** [comment]
I'd be looking at the in-game addons list to find Attune.
But yeah, the problem looks like this to me:
```
[string "@Details\core\network.lua"]:404: in function `func'
[string "@Details\core\network.lua"]:648: in function `?'
```

Mentions of BugSack, AtlasLoot & Attune seem to just be from shared libraries.
