### ISSUE TITLE
Error on load in Dragonflight Beta

### ISSUE THREAD

**Issue by fraerie** [funkydude/BugSack#67]
## Describe the problem
I get an immediate "fatality" error on log in if I have BugSack loaded in Dragonflight beta
The game client immediately reloads and disables the addon - I don't have details of exactly what is happening as I don't have a read out of the error.
I also have buggrabber loaded but it now errors that there is nowhere to display the captured bugs.

### What steps will reproduce the problem?

1.  
2.  
3.

**Comment by funkydude** [comment]
Nothing I can do about this. It will be fixed by Blizz at some point.
