### ISSUE TITLE
Rapid Bugs Prevent Scroll Back to Previous Bugs

### ISSUE THREAD

**Issue by Xatan** [funkydude/BugSack#68]
## Describe the problem
The most recent bug is displayed on top of the display, but if this bug is occurring very fast then it is not possible to scroll backwards via the Previous button to see the first bug in the addon which caused the later, rapidly-occurring bugs. 
This makes it really hard to deduce what caused the first bug because the call stack cannot be seen for the first bug.
The summary 5-bug list view does not help because it does not show the call stacks.
I just spent many hours commenting out & disabling bits of coding just to suppress coding which was bugging out because of the first bug. Eventually, after many hours of work, I could see the first bug's call stack, and then I solved the first bug (and all the other bugs disappeared) in minutes.  I could slowly workaround this problem as a programmer, but ordinary players/addon-users are often asked to supply the screenshot of bugsack  showing the first bug that failed in an addon,  but frequently this cannot be done because the user cannot use the Previous button to scroll back if secondary bugs are occurring really fast.

### What steps will reproduce the problem?

1.  Have a bug which prevents some window(s) in an addon not to be created.
2.  Have a frequently called event handler such as OnUpdate check an attribute on a window which failed to be created, to cause a rapidly occurring nil value error bug to occur.
3.  Try and press the Previous button to see the first bug's call stack, but the secondary bugs will keep popping the secondary bug(s) display to the top, over-riding the Previous button click, so the first bug cannot be reached to see it's call stack.

### What version of the addon are you using? (Stating 'latest' is not useful)
[v9.2.5](https://github.com/funkydude/BugSack/tree/v9.2.5) (2022-08-28)

**Comment by funkydude** [comment]
Closed by #69
