### ISSUE TITLE
Buggrabber LUA error? DF Pre-patch

### ISSUE THREAD

**Issue by fraerie** [funkydude/BugSack#77]
## Describe the problem
I'm not sure if this is Mapster or Buggrabber - have logged a ticket with Mapster as well

### What steps will reproduce the problem?

1.  Open a map with Mapster loaded
2.  
3.  

### What version of the addon are you using? (Stating 'latest' is not useful)
!BugGrabber-v10.0.0
Mapster-1.10.0

### Do you have an error log of what happened?

2x [ADDON_ACTION_BLOCKED] AddOn 'Mapster' tried to call the protected function 'MultiBarLeftButton12:SetAttribute()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/ActionButton.lua"]:355: in function `UpdatePressAndHoldAction'
[string "@Interface/FrameXML/ActionButton.lua"]:409: in function `Update'
[string "@Interface/FrameXML/ActionButton.lua"]:797: in function `OnEvent'
[string "@Interface/FrameXML/ActionButton.lua"]:216: in function <Interface/FrameXML/ActionButton.lua:213>

**Comment by funkydude** [comment]
This place is for reporting issues with BugSack, not Mapster.
