### ISSUE TITLE
Deferred XML Node object named ...

### ISSUE THREAD

**Issue by SiegaPlays** [funkydude/BugSack#8]
I have gotten this weird error the past day or so, not quite sure what to make out of it, and well, I can not report it directly on the BugGrabber addon.

---------------------

129x Deferred XML Node object named L_UIDropDownListTemplate already exists
!BugGrabber\BugGrabber.lua:578: in function <!BugGrabber\BugGrabber.lua:578>

Locals:
nil

---------------------

129x Deferred XML Node object named L_UIDropDownMenuTemplate already exists
!BugGrabber\BugGrabber.lua:578: in function <!BugGrabber\BugGrabber.lua:578>

Locals:
nil

---------------------

172x Deferred XML Node object named L_UIDropDownMenuButtonTemplate already exists
!BugGrabber\BugGrabber.lua:578: in function <!BugGrabber\BugGrabber.lua:578>

Locals:
nil

**Comment by funkydude** [comment]
Addon error, nothing to do with BugSack (or buggrabber).
Looks like one of your addons is using a library for dropdowns, and that library is causing this issue.

**Comment by SiegaPlays** [comment]
I switched off the addons until I got the one that stopped the problem and could repeat it by enabling it again. Hope it is the only one. Broker Keystone. Reporting on their addon instead.

Thank you

**Comment by funkydude** [comment]
Thanks for the work in tracking this. I checked, it uses a library called LibUIDropDownMenu.
It seems someone has already reported this issue to their author:
https://www.wowace.com/projects/libuidropdownmenu/issues/1
I would recommend giving it a bump and expanding on the fact that this issue now appears in game and affects any addon using that library.

There are quite a few addons using it:
https://www.wowace.com/projects/libuidropdownmenu/relations/dependents
