### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by blecaplol** [funkydude/BugSack#83]
7355x FrameXML/EditModeSystemTemplates.lua:631: attempt to perform arithmetic on local 'offsetY' (a nil value)
[string "@FrameXML/EditModeSystemTemplates.lua"]:631: in function `GetBottomAnchoredHeight'
[string "@FrameXML/EditModeUtil.lua"]:39: in function `GetBottomActionBarHeight'
[string "@FrameXML/UIParent.lua"]:3083: in function `UIParentManageFramePositions'
[string "@FrameXML/UIParent.lua"]:2570: in function <FrameXML/UIParent.lua:2557>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3113: in function `UIParent_ManageFramePositions'
[string "@FrameXML/EditModeManager.lua"]:640: in function <FrameXML/EditModeManager.lua:607>
[string "=[C]"]: in function `UpdateBottomActionBarPositions'
[string "@FrameXML/EditModeManager.lua"]:554: in function `UpdateActionBarLayout'
[string "@FrameXML/EditModeSystemTemplates.lua"]:655: in function `UpdateGridLayout'
[string "@FrameXML/ActionButton.lua"]:368: in function `UpdateAction'
[string "@FrameXML/ActionButton.lua"]:795: in function `OnEvent'
[string "@FrameXML/ActionButton.lua"]:216: in function <FrameXML/ActionButton.lua:213>

Locals:
self = MainMenuBar {
 0 = <userdata>
 QuickKeybindRightShadow = Texture {
 }
 UpdateSystemSettingAlwaysShowButtons = <function> defined @FrameXML/EditModeSystemTemplates.lua:772
 UpdateMagnetismRegistration = <function> defined @FrameXML/EditModeSystemTemplates.lua:506
 GetSnapOffsets = <function> defined @FrameXML/EditModeSystemTemplates.lua:411
 UpdateFrameStrata = <function> defined @FrameXML/ActionBar.lua:194
 UpdateButtonArt = <function> defined @FrameXML/EditModeSystemTemplates.lua:669
 IsFrameAnchoredToMe = <function> defined @FrameXML/EditModeSystemTemplates.lua:469
 buttonTemplate = "MainBarActionBarButtonTemplate"
 ShowBase = <function> defined =[C]:-1
 IsShown = <function> defined @FrameXML/ActionBar.lua:286
 GetSelectionOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:363
 ResetToDefaultPosition = <function> defined @FrameXML/EditModeSystemTemplates.lua:148
 RefreshButtonArt = <function> defined @FrameXML/EditModeSystemTemplates.lua:662
 GetScaledSelectionSides = <function> defined @FrameXML/EditModeSystemTemplates.lua:355
 SelectSystem = <function> defined @FrameXML/EditModeSystemTemplates.lua:534
 buttonArtDirty = false
 GetFrameMagneticEligibility = <function> defined @FrameXML/EditModeSystemTemplates.lua:489
 AddLayoutChildren = <function> defined @SharedXML/LayoutFrame.lua:48
 IsBelowFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:322
 UpdateSystemSettingIconSize = <function> defined @FrameXML/EditModeSystemTemplates.lua:714
 SetScaleBase = <function> defined =[C]:-1
 HasActiveChanges = <function> defined @FrameXML/EditModeSystemTemplates.lua:244
 GetScaledCenter = <function> defined @FrameXML/EditModeSystemTemplates.lua:348
 DoesSettingDisplayValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:268
 OnLoad = <function> defined @FrameXML/MainMenuBar.lua:6
 UpdateDisplayInfoOptions = <function> defined @FrameXML/EditModeSystemTemplates.lua:279
 ActionBarPageNumber = Frame {
 }
 settingDisplayInfoMap = <table> {
 }
 addSystemIndexToName = true
 IsLayoutFrame = <function> defined @SharedXML/LayoutFrame.lua:36
 DoesSettingValueEqual = <function> defined @FrameXML/EditModeSystemTemplates.lua:263
 MarkDirty = <function> defined @SharedXML/LayoutFrame.lua:90
 ShouldResetSettingsDialogAnchors = <function> defined @FrameXML/EditModeSystemTemplates.lua:91
 dirtySettings = <table> {
 }
 UpdateGridLayout = <function> defined @FrameXML/EditModeSystemTemplates.lua:648
 IsToTheLeftOfFrame = <function> defined @FrameXML/EditModeSystemTemplates.lua:304
 GetSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:288
 hasActiveChanges = false
 OnSystemLoad = <function> defined @FrameXML/EditModeSystemTemplates.lua:3
 ClearFrameSnap = <function> defined @FrameXML/EditModeSystemTemplates.lua:448
 GetCombinedCenterOffset = <function> defined @FrameXML/EditModeSystemTemplates.lua:398
 SetupSettingsDialogAnchor = <function> defined @FrameXML/EditModeSystemTemplates.lua:232
 IsShownOverride = <function> defined @FrameXML/ActionBar.lua:286
 dirty = false
 SetPointBase = <function> defined =[C]:-1
 UpdateSystem = <function> defined @FrameXML/EditModeSystemTemplates.lua:586
 UpdateShownButtons = <function> defined @FrameXML/ActionBar.lua:198
 UpdateDirtySettings = <function> defined @FrameXML/EditModeSystemTemplates.lua:112
 BreakSnappedFrames = <function> defined @FrameXML/EditModeSystemTemplates.lua:431
 HideOverride = <function> defined @FrameXML/ActionBar.lua:313
 VehicleLeaveButton = MainMenuBarVehicleLeaveButton {
 }
 systemIndex = 1
 snappedFrames = <table> {
 }
 SetShownOverride = <function> defined @FrameXML/ActionBar.lua:298
 SetPointOverride = <function> defined @

**Comment by funkydude** [comment]
Unrelated to BugSack.
