### ISSUE TITLE
Loss of control frame error only with bugsack/grabber activated

### ISSUE THREAD

**Issue by tonyrapz** [funkydude/BugSack#84]

**Comment by tonyrapz** [comment]
76x FrameXML/LossOfControlFrame.lua:85: bad argument #1 to 'SetAlpha' (Usage: self:SetAlpha(alpha))
[string "=[C]"]: in function `SetAlpha'
[string "@FrameXML/LossOfControlFrame.lua"]:85: in function <FrameXML/LossOfControlFrame.lua:77>

Locals:
(*temporary) = LossOfControlFrame {
 0 = <userdata>
 AbilityName = FontString {
 }
 RedLineTop = Texture {
 }
 blackBg = Texture {
 }
 startTime = 26557.804688
 Cooldown = Cooldown {
 }
 priority = 5
 fadeTime = 1.493000
 Anim = AnimationGroup {
 }
 TimeLeft = Frame {
 }
 RedLineBottom = Texture {
 }
 Icon = Texture {
 }
 spellID = 372529
}
(*temporary) = 2.986000

**Comment by funkydude** [comment]
This isn't an error in BugSack.
