### ISSUE TITLE
Game tooltip

### ISSUE THREAD

**Issue by nenad9595** [funkydude/BugSack#85]
[v10.0.2](https://github.com/funkydude/BugSack/tree/v10.0.2) (2022-11-15) this is the version

when i install weakauras [5.3.4] 3 days ago was updated  this happens

2x [string "return function() local local_env = aura_en..."]:68: attempt to index field 'game_tooltip' (a nil value)
[string "return function() local local_env = aura_env or {}"]:68: in function <[string "return function() local local_env = aura_en..."]:64>
[string "=[C]"]: in function `GameTooltip_SetDefaultAnchor'
[string "@FrameXML/GameTooltip.lua"]:954: in function `SetWorldCursor'
[string "@FrameXML/UIParent.lua"]:1476: in function <FrameXML/UIParent.lua:1399>

Locals:
tooltip = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetAchievementByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined =[C]:-1
 SetVoidWithdrawalItem = <function> defined =[C]:-1
 SetEnhancedConduit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 hasMoney = 1
 SetExistingSocketGem = <function> defined =[C]:-1
 SetInfoBackdropStyle = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:338
 SetTotem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 numMoneyFrames = 1
 SetSocketGem = <function> defined =[C]:-1
 SetRuneforgeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 waitingForData = false
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined =[C]:-1
 OnLoad = <function> defined @FrameXML/GameTooltip.lua:927
 GetUnit = <function> defined @FrameXML/GameTooltip.lua:994
 SetOwnedItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 shoppingTooltips = <table> {
 }
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPetAction = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLFGDungeonReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWeeklyReward = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetMerchantCostItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 updateTooltipTimer = 0.083000
 BottomOverlay = Texture {
 }
 supportsItemComparison = true
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:990
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsDataRefresh = true
 ProcessLines = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:293
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined =[C]:-1
 StatusBar = GameTooltipStatusBar {
 }
 SetBuybackItem = <function> defined =[C]:-1
 SetLootRollItem = <function> defined =[C]:-1
 SetPvpBrawl = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBagItem = <function> defined =[C]:-1
 SetTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAction = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:236
 SetCompanionPet = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInventoryItemByID = <function> defined @SharedXML
### What steps will reproduce the problem?

1.  
2.  
3.

**Comment by funkydude** [comment]
Nothing to do with BugSack.
