### ISSUE TITLE
Why doesn't !BugGrabber get updated when BugSack gets updated?

### ISSUE THREAD

**Issue by b-morgan** [funkydude/BugSack#86]
## Describe the problem
BugSack .toc was updated but its dependency, !BugGrabber, was not updated. BugSack complains that it requires !BugGrabber and tells me to get it from the same place I got BugSack (which is a lie).

### What steps will reproduce the problem?

1.  Do not check "Load out of date AddOns"
2.  Login
3.  Error message printed

### What version of the addon are you using? (Stating 'latest' is not useful)
V10.0.4

### Do you have an error log of what happened?
N/A

### Any additional information? (example: WoW language if not English)
!BugGrabber should either have a public github repository (linked to from here) or the !BugGrabber files should be included in this github repository.

**Comment by funkydude** [comment]
BugGrabber was updated prior to BugSack. I assume you are downloading from wago instead of CurseForge, which you failed to mention.

I forgot to update it on wago also, this has now been resolved.
