### ISSUE TITLE
Is it possible for BugGrabber itself to cause an issue? No other addons have updated and I am receiving a previously unseen error and am unable to use consumables from bags.

### ISSUE THREAD

**Issue by Cavanoskus** [funkydude/BugSack#96]
## Describe the problem
I apologize if I've misunderstood the error message pasted below, but this issue appeared specifically after updating BugGrabber, and the other addon it references did not produce problems before the BugGrabber update.

After updating BugGrabber to v10.1.5, and **with no changes to any other addons,** a new error has appeared and I am now unable to right-click to use any consumable item from my inventory. I can still use the items from the action bar. I am using Bagnon 10.1.10 and I reported this over there as well, but this issue appeared _only_ after updating BugGrabber at about 10 PM on Sept. 21 and was not present before the BugGrabber update. The error (pasted below) says Bagnon tried to call an unknown protected function and then lists BugGrabber several times; considering everything worked fine until the BugGrabber update (and nothing else was updated) it makes me wonder if somehow BugGrabber itself is causing this issue?

Here is the issue I posted over at Bagnon: https://github.com/Jaliborc/Bagnon/issues/1791

### What steps will reproduce the problem?

1.  In Classic Era, have BugGrabber v10.1.5 installed and Bagnon 10.1.10 installed.
2.  Attempt to use any consumable item directly from bags (recipes, food, etc).
3.  Item is not used and below error pops up.

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)
No screenshot, but error posted below.

### What version of the addon are you using? (Stating 'latest' is not useful)
BugGrabber v10.1.5.

### Do you have an error log of what happened?
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Bagnon' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame_Shared.lua"]:1273: in function `ContainerFrameItemButton_OnClick'
[string "*ContainerFrame.xml:165_OnClick"]:13: in function <[string "*ContainerFrame.xml:165_OnClick"]:1>
[string "=[C]"]: ?

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

### Any additional information? (example: WoW language if not English)
Both addons installed and updated via CurseForge client if that matters.

**Comment by funkydude** [comment]
Unrelated to BugGrabber or BugSack. Caused by a recent mini-patch pushed by Blizzard.
