### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Powermints** [funkydude/BugSack#97]
YO, bugsack gives out such errors during the battle

202x [string "pCQS()"]:1: attempt to call global 'pCQS' (a nil value)
[string "pCQS()"]:1: in main chunk
[string "=[C]"]: in function RunScript'
[string "@FrameXML/ChatFrame.lua"]:2221: in function ?'
[string "@FrameXML/ChatFrame.lua"]:4952: in function <FrameXML/ChatFrame.lua:4898>
[string "=[C]"]: in function ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4615: in function ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:2994: in function <FrameXML/ChatFrame.lua:2987>
[string "=[C]"]: ?
[string "=[C]"]: in function UseAction'
[string "@FrameXML/SecureTemplates.lua"]:343: in function handler'
[string "@FrameXML/SecureTemplates.lua"]:625: in function <FrameXML/SecureTemplates.lua:569>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:266: in function <FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@FrameXML/SecureHandlers.lua"]:296: in function <FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

as a result, the performance of the game decreases, how to fix it?

**Comment by funkydude** [comment]
Not a BugSack problem.
