### ISSUE TITLE
Sorted and Buggrabber

### ISSUE THREAD

**Issue by Mechrior** [funkydude/BugSack#98]
### What steps will reproduce the problem?

1.  enter wow or after reload
2.  try to right click an openable item in sorted
3.  bagsack shows an error

### What version of the addon are you using? (Stating 'latest' is not useful)
BugGrabber 10.1.6
Bugsack 10.1.8
Sorted 2.1.12

### Do you have an error log of what happened?
1x [ADDON_ACTION_FORBIDDEN] AddOn 'Sorted' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `UseContainerItem'
[string "@FrameXML/ContainerFrame.lua"]:1424: in function `ContainerFrameItemButton_OnClick'
[string "@FrameXML/ContainerFrame.lua"]:1476: in function <FrameXML/ContainerFrame.lua:1463>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by funkydude** [comment]
Not a BugSack issue.
