### ISSUE TITLE
BugSack doesn't "see" BugGrabber is installed

### ISSUE THREAD

**Issue by Kithhurrn** [funkydude/BugSack#99]
## Describe the problem
BugSack gives error that BugGrabber is required when BugGrabber IS already installed and shows as loaded in AddOn list. Happens in clean install of WoW retail with no other addons. Has been happening since DF xpac release with all releases of both BugGrabber and BugSack installed. Have tried manually installing the AddOns as well as using Curse installer. Even had the opportunity a few months ago to reinstall WoW retail on a clean Win10 install with just BugSack & BugGrabber and still BugSack didn't see BugGrabber

### What steps will reproduce the problem?

1.  Clean install of WoW retail (reinstall the game after uninstalling WoW and removing all files/folders left, especially made sure to remove old WTF and AddOn folders. Also have removed BNet folder from AppData.)
2.  Launch WoW retail and login to any character. 
3.  

### Consider attaching a screenshot below to help describe your issue (Attach directly, do not link to other websites)

![WoWScrnShot_122923_062616](https://github.com/funkydude/BugSack/assets/26926781/13a0b9db-3788-42ae-a047-1db936c91460)

### What version of the addon are you using? (Stating 'latest' is not useful)
Currently BugGrabber v10.2.1 with BugSack v10.2.1 w/DF 10.2.0

### Do you have an error log of what happened?
Just the error msg in Chat that can be seen in the screenshot.

**Comment by tim-livingston** [comment]
Also experiencing this, with same steps to reproduce. Have deleted both BugSack/BugGrabber, wiped WTF, and even done clean reinstall and still getting the same error message where the addons do not see each other.

Currently using BugGrabber with BugSack disabled and it is working fine (albeit with challenging in-game UX).

**Comment by funkydude** [comment]
You've installed some malicious addon that purposely disabled the special `Blizzard_Deprecated` addon that BugGrabber assumes is loaded. Unfortunately this change is "permanent" in the sense it will remain disabled even after removing the addon that did it.

A new update to BugGrabber will compensate for this.
